config/routes.rb
Rails.application.routes.draw do
  resources :gardens do
    resources :plants, only: [:new, :create]
  end
  root to: "gardens#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  has_many :plants

  validates :name, presence: true
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden

  validates :color, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden, only: [:show, :edit, :update, :destroy]

  # GET /gardens
  # GET /gardens.json
  def index
    @gardens = Garden.all
  end

  # GET /gardens/1
  # GET /gardens/1.json
  def show
  end

  # GET /gardens/new
  def new
    @garden = Garden.new
  end

  # GET /gardens/1/edit
  def edit
  end

  # POST /gardens
  # POST /gardens.json
  def create
    @garden = Garden.new(garden_params)

    respond_to do |format|
      if @garden.save
        format.html { redirect_to @garden, notice: 'Garden was successfully created.' }
        format.json { render :show, status: :created, location: @garden }
      else
        format.html { render :new }
        format.json { render json: @garden.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gardens/1
  # PATCH/PUT /gardens/1.json
  def update
    respond_to do |format|
      if @garden.update(garden_params)
        format.html { redirect_to @garden, notice: 'Garden was successfully updated.' }
        format.json { render :show, status: :ok, location: @garden }
      else
        format.html { render :edit }
        format.json { render json: @garden.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gardens/1
  # DELETE /gardens/1.json
  def destroy
    @garden.destroy
    respond_to do |format|
      format.html { redirect_to gardens_url, notice: 'Garden was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_garden
      @garden = Garden.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def garden_params
      params.require(:garden).permit(:name, :category, :location)
    end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController

  before_action :garden_set

  def new
    @plant = Plant.new
  end

  def create
    @plant = Plant.new(plant_params)
    @plant.garden = @garden
    if @plant.save
      redirect_to @garden
    else
      render :new
    end
  end

  private

  def garden_set
    @garden = Garden.find(params[:garden_id])
  end

  def plant_params
    params.require(:plant).permit(:name, :color, :size)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardens/_card.html.erb
<%= link_to garden_path(garden) do %>
  <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://images.pexels.com/photos/126271/pexels-photo-126271.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940');">
    <div class="card-category">Popular</div>
    <div class="card-description">
      <h2><%= garden.name %></h2>
      <p>Very cool city, the best</p>
    </div>
    <img class="card-user" src="https://kitt.lewagon.com/placeholder/users/tgenaitay">
  </div>
<% end %>
<%#= link_to "", path %>

app/views/gardens/_form.html.erb
<%= form_with(model: garden, local: true) do |form| %>
  <% if garden.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(garden.errors.count, "error") %> prohibited this garden from being saved:</h2>

      <ul>
      <% garden.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gardens/edit.html.erb
<h1>Editing Garden</h1>

<%= render 'form', garden: @garden %>

<%= link_to 'Show', @garden %> |
<%= link_to 'Back', gardens_path %>

app/views/gardens/index.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.pexels.com/photos/257360/pexels-photo-257360.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940');">
  <div class="banner-content">
    <h1>Welcome to my garden site </h1>
    <p>Lets plant some plants</p>
    <a class="btn btn-primary btn-lg">Start now</a>
  </div>
</div>
<div class="container">
  <div class="row">
    <br>
    <% @gardens.each do |g| %>
      <div class="col col-xs-12 col-sm-4">
        <%= render 'card', garden: g %>
      </div>
    <% end %>
  </div>
</div>
<br>
<%= link_to 'New Garden', new_garden_path %>

app/views/gardens/new.html.erb
<h1>New Garden</h1>

<%= render 'form', garden: @garden %>

<%= link_to 'Back', gardens_path %>

app/views/gardens/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @garden.name %>
</p>
<p>
  <strong>Category:</strong>
  <%= @garden.category %>
</p>
<p>
  <strong>Location:</strong>
  <%= @garden.location %>
</p>
<ul><% @garden.plants.each do |p| %>
    <li> <%= p.color %> <%= p.name %></li>
  <% end %></ul>
<%= link_to 'Edit', edit_garden_path(@garden) %> |
<%= link_to 'Back', gardens_path %>
<%= link_to 'Create New Plants', new_garden_plant_path(@garden)  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gardens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/plants/new.html.erb
<%= simple_form_for [@garden, @plant] do |f| %>
  <%= f.input :name, label: "Please enter a name", autofocus: true %>
  <%= f.input :color, placeholder: "e.g. blue eggplant", hint: "this is required" %>
  <%= f.input :size %>
  <%= f.association :garden, collection: Garden.all %>
  <%= f.submit %>
<% end %>